import type { ResourceConfig } from "@/components/ResourceManager";

export const resourceConfigs: ResourceConfig[] = [
  {
    title: "Leads",
    basePath: "/api/v1/leads",
    columns: [
      { key: "id", label: "ID" },
      { key: "firstName", label: "First name" },
      { key: "lastName", label: "Last name" },
      { key: "email", label: "Email" },
      { key: "source", label: "Source" },
      { key: "createdDate", label: "Created" },
    ],
    fields: [
      { key: "firstName", label: "First name", type: "text", required: true },
      { key: "lastName", label: "Last name", type: "text", required: true },
      { key: "email", label: "Email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "source", label: "Source", type: "text" },
    ],
  },
  {
    title: "Clients",
    basePath: "/api/v1/clients",
    columns: [
      { key: "id", label: "ID" },
      { key: "firstName", label: "First name" },
      { key: "lastName", label: "Last name" },
      { key: "email", label: "Email" },
      { key: "isActive", label: "Active" },
      { key: "isSuspended", label: "Suspended" },
    ],
    fields: [
      { key: "firstName", label: "First name", type: "text", required: true },
      { key: "lastName", label: "Last name", type: "text", required: true },
      { key: "email", label: "Email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
    ],
    deletable: false,
  },
  {
    title: "Membership Templates",
    basePath: "/api/v1/membership-templates",
    columns: [
      { key: "id", label: "ID" },
      { key: "name", label: "Name" },
      { key: "description", label: "Description" },
      { key: "price", label: "Price" },
    ],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "description", label: "Description", type: "text" },
      { key: "price", label: "Price", type: "number" },
    ],
  },
  {
    title: "Memberships",
    basePath: "/api/v1/memberships",
    columns: [
      { key: "id", label: "ID" },
      { key: "clientId", label: "Client ID" },
      { key: "templateId", label: "Template ID" },
      { key: "isActive", label: "Active" },
      { key: "autoRenew", label: "Auto-renew" },
    ],
    fields: [
      { key: "clientId", label: "Client ID", type: "number", required: true },
      { key: "templateId", label: "Template ID", type: "number", required: true },
    ],
    deletable: false,
  },
  {
    title: "Invoices",
    basePath: "/api/v1/invoices",
    columns: [
      { key: "id", label: "ID" },
      { key: "clientId", label: "Client ID" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
      { key: "issueDate", label: "Issued" },
    ],
    fields: [],
    creatable: false,
    deletable: false,
  },
  {
    title: "Discounts",
    basePath: "/api/v1/discounts",
    columns: [
      { key: "id", label: "ID" },
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "value", label: "Value" },
      { key: "isActive", label: "Active" },
    ],
    fields: [],
    creatable: false,
    deletable: false,
  },
  {
    title: "Classes",
    basePath: "/api/v1/classes",
    columns: [
      { key: "id", label: "ID" },
      { key: "name", label: "Name" },
      { key: "program", label: "Program" },
      { key: "startDateTime", label: "Start" },
      { key: "endDateTime", label: "End" },
      { key: "capacity", label: "Capacity" },
    ],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "program", label: "Program", type: "text" },
      { key: "startDateTime", label: "Start", type: "datetime", required: true },
      { key: "endDateTime", label: "End", type: "datetime", required: true },
      { key: "capacity", label: "Capacity", type: "number" },
      { key: "location", label: "Location", type: "text" },
    ],
    deletable: false,
  },
  {
    title: "Reservations",
    basePath: "/api/v1/reservations",
    columns: [
      { key: "id", label: "ID" },
      { key: "classId", label: "Class ID" },
      { key: "clientId", label: "Client ID" },
      { key: "status", label: "Status" },
    ],
    fields: [],
    creatable: false,
    deletable: false,
  },
  {
    title: "Sign-ins",
    basePath: "/api/v1/sign-ins",
    columns: [
      { key: "id", label: "ID" },
      { key: "classId", label: "Class ID" },
      { key: "clientId", label: "Client ID" },
      { key: "signedInAt", label: "Signed in" },
    ],
    fields: [],
    creatable: false,
    deletable: false,
  },
  {
    title: "Workouts",
    basePath: "/api/v1/workouts",
    columns: [
      { key: "id", label: "ID" },
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "type", label: "Type", type: "text" },
      { key: "description", label: "Description", type: "text" },
      { key: "components", label: "Components", type: "text" },
    ],
  },
];
